To https://github.com/rajkumar-beep/ecs-cicd-ha-project-9.git
   ee87c47..d33f010  main -> main
test@test-VirtualBox:~/ecs-cicd-ha-project-9$ cd .github/workflows/
test@test-VirtualBox:~/ecs-cicd-ha-project-9/.github/workflows$ nano ci-cd.yml
  GNU nano 6.2                                                                                         ci-cd.yml *
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg APP_VERSION=${{ steps.tag.outputs.TAG }} \
            -t ${{ secrets.DOCKER_USERNAME }}/ecs-ha-app:${{ steps.tag.outputs.TAG }} \
            -t ${{ secrets.DOCKER_USERNAME }}/ecs-ha-app:latest \
            .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ecs-ha-app:${{ steps.tag.outputs.TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/ecs-ha-app:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Update ECS Task Definition with new image
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition-arn: ${{ secrets.ECS_TASK_DEFINITION_ARN }}
          container-name: ecs-ha-app
          image: ${{ secrets.DOCKER_USERNAME }}/ecs-ha-app:${{ steps.tag.outputs.TAG }}

      - name: Deploy to ECS Service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ secrets.ECS_SERVICE_NAME }}
          cluster: ${{ secrets.ECS_CLUSTER_NAME }}
          wait-for-service-stability: true

      - name: Print Success
        run: |
          echo "✅ Deployed: ${{ s

